Metrics/BlockLength:
  ExcludedMethods:
    - 'context'
    - 'describe'
    - 'new'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 200

Style/ParallelAssignment:
  Enabled: false

Style/MixinUsage:
  Enabled: false
